FlowRouter.route('/',{
     action(){
       BlazeLayout.render('home')
       }
});

FlowRouter.route('/signup',{
     action(){
       BlazeLayout.render('signup')
       }
});
FlowRouter.route('/doctor',{
     action(){
       BlazeLayout.render('doctor')
       }
});
FlowRouter.route('/quiz_dif',{
     action(){
       BlazeLayout.render('quiz_dif')
       }
});
FlowRouter.route('/quiz_ddf',{
     action(){
       BlazeLayout.render('quiz_ddf')
       }
});
FlowRouter.route('/quiz_eot',{
     action(){
       BlazeLayout.render('quiz_eot')
       }
});
